### ISSUE TITLE
helpWidget doesn't appear when `modules` attribute passed

### ISSUE THREAD

**Issue by mrac** [zalando/solution-center-header#13]
We now pass ```modules``` attribute and the helpWidget icon doesn't appear anymore.

I checked and it seems the icon is hidden because the helpWidged doesn't load at all.

**Probable cause:**

In our code the modules value is resolved directly by $resource method, without calling a promise success callback. The $resource method immediately returns an empty reference array. Once the data is returned from the server the existing reference is populated with the actual data.

We do:
```
$scope.modules = UserServiceModule.query();
```
instead of using a promise success callback:
```
UserServiceModule.query().$promise.then(function(modules) {
    $scope.modules = modules;
});
```
We could use the second approach, but then the loadHelpWidget would not be called with modules parameter, because 'modules' is undefined in the beginning (which is actually the second issue).

So in the header controller, the $watch is triggered only once, when the modules object is truthy, but the length is still 0. It will not be triggered again when the data is populated, because the object is still the same.

```
if (!vm.modules) {
        // if no modules provided, load the help widget with just default product
        loadHelpWidget();
      } else {
        // otherwise, wait for modules to be populated then load the widget
        $scope.$watch(
          function () {
            return vm.modules;
          },
....
```

**Probable solution:**

We could change the trigger for a watch to take that case into account (example below), or watch deeply, or watch the length.

```
$scope.$watch(function () {
   return vm.modules && (vm.modules.$resolved !== false);
});
```

**Comment by mrac** [comment]
And to solve the second issue, the $watch could be registered always, not just in the case when ```vm.modules``` is initially truthy.

**Comment by mrac** [comment]
Or better solution would be to check for $attrs.modules instead of this.modules in if() statement:
```
if (!$attrs.modules) {
    // if no modules provided, load the help widget with just default product
    loadHelpWidget();
``` 
In such case we just check if the modules attribute is defined or not, without checking it's value.

**Comment by cjhowald** [comment]
I will change the first check to be based on `$attrs.modules` as that is the intended logic.

For the issue of passing in an empty array and then populating it later, `$watchCollection` solves the problem.
